import { KINDS, fmt, clone, sharedGeometry, variantFields, compareVariant, historyEntry } from './workflow-model.js';
import { validEntry } from './entry-validation.js';
import { MATERIALS } from './calculations.js';
import { createWorkspaceStore } from './workspace-store.js';
import { trapFocus } from './dialog-focus.js';
import { dataToolsBody, initDataTools } from './data-tools.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const field=(id,label,value='',hint='')=>`<div><label for="${id}">${label}</label><input id="${id}" inputmode="decimal" value="${esc(value)}">${hint?`<small>${hint}</small>`:''}</div>`;
const select=(id,label,options)=>`<div><label for="${id}">${label}</label><select id="${id}">${options.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('')}</select></div>`;
const panel=(id,title,body)=>`<section id="${id}" class="work-panel" hidden role="dialog" aria-modal="true" aria-labelledby="${id}-title"><div class="work-panel-heading"><h3 id="${id}-title" tabindex="-1">${title}</h3><button type="button" class="secondary-button" data-close-panel>Zavřít</button></div><p class="panel-message" role="status"></p>${body}</section>`;
const geometryIds={material:'shared-material',technique:'shared-technique',qualityClass:'shared-class',thickness:'shared-thickness',diameter:'shared-diameter',sfd:'shared-sfd',gap:'shared-gap',pathMode:'shared-path',penetrated:'shared-penetrated'};
const labels={technique:'Technika',qualityClass:'Třída',thickness:'Tloušťka (mm)',diameter:'Průměr De (mm)',distance:'Vzdálenost (mm)',sourceDistance:'Zdroj–první povrch (mm)',gap:'Mezera (mm)',focus:'Ohnisko (mm)',planar:'Planární vady',mode:'Zdroj reference',material:'Materiál',film:'Film',voltage:'Napětí (kV)',current:'Proud (mA)',exposure:'Referenční E (mA·min)',referenceDistance:'Referenční SFD (mm)',referenceName:'Vlastní reference',activity:'Referenční aktivita (GBq)',referenceTime:'Datum aktivity',exposureTime:'Datum expozice',fdd:'FDD (mm)',roi:'Místo měření',flush:'Zarovnaný svar',cp1:'CP I',iqiConfirmed:'Potvrzené IQI',kind:'Druh SNR',measured:'Naměřené SNR',srb:'SR_b (mm)',magnification:'Zvětšení',seconds:'Skutečný čas (s)',name:'Název měření',setup:'Sestava',screens:'Fólie / filtrace',scan:'Skener',delay:'Prodleva (min)',measuredAt:'Datum měření'};
const values={outside:'Jedna stěna · zdroj vně',inside:'Jedna stěna · zdroj uvnitř',single:'Jedna stěna',double:'DWSI',dwsi:'DWSI',dwdi:'DWDI',chart:'Výrobní diagram',manual:'Vlastní reference',weld:'Svar',haz:'HAZ / základní materiál',raw:'SNR',normalized:'SNR_N',...MATERIALS};
export function initWorkflow({document:d=globalThis.document,app,store:provided}={}){
 const w=d.defaultView,by=id=>d.getElementById(id),abort=new w.AbortController(),on=(el,event,fn)=>el.addEventListener(event,fn,{signal:abort.signal});
 const store=provided||createWorkspaceStore({indexedDB:w.indexedDB,onChange:refresh});
 let entries=[],base=null,variants=[],activePanel=null,returnFocus=null,readyForStorage=false,stopped=false,historyPage=0,historyIndex=[],jobNames=new Map();
 const PAGE_SIZE=50;
 const message=(text,error=false)=>{const target=activePanel?by(activePanel).querySelector('.panel-message'):by('workflow-message');target.textContent=text;target.dataset.error=String(error);};
 by('workflow-panels').innerHTML=
 panel('data-panel','Offline a zálohy',dataToolsBody)+
 panel('job-panel','Nová zakázka','<label for="job-name">Název nebo číslo zakázky</label><input id="job-name" maxlength="120" placeholder="Např. RT-2026-042"><div class="work-panel-actions"><button id="job-create" type="button" class="primary-button">Vytvořit zakázku</button></div>')+
 panel('history-panel','Historie výpočtů',`<div class="work-grid">${select('history-scope','Rozsah historie',[['current','Aktuální zakázka'],['all','Všechny zakázky']])}<div><label for="history-search">Najít díl nebo svar</label><input id="history-search" type="search" placeholder="Číslo svaru, díl, zakázka…"></div></div><p>Každý záznam uchovává původní výsledek a verzi modelu. Otevření přenese vstupy do aktuálního kalkulátoru.</p><div id="history-list"></div><nav class="history-pages" aria-label="Stránky historie"><button id="history-prev" type="button" class="secondary-button">Předchozí</button><p id="history-page-status" role="status"></p><button id="history-next" type="button" class="secondary-button">Další</button></nav>`)+
 panel('geometry-panel','Společná geometrie',`<p>Vyplňte geometrii a vyberte, kam ji přenést. Následné úpravy jednotlivých kalkulátorů jsou samostatné.</p><div class="work-grid">${select('shared-material','Materiál',Object.entries(MATERIALS))}${select('shared-technique','Technika',[['outside','Trubka · jedna stěna, zdroj vně'],['inside','Trubka · jedna stěna, zdroj uvnitř'],['dwsi','Dvě stěny · DWSI'],['dwdi','Dvě stěny · DWDI'],['flat','Plochý díl · jedna stěna']])}${select('shared-class','Třída',[['B','B'],['A','A']])}${field('shared-thickness','Jedna stěna t (mm)',10)}${field('shared-diameter','Vnější průměr De (mm)',219)}${field('shared-sfd','Zdroj–film SFD (mm)',1000)}${field('shared-gap','Mezera předmět–film (mm)',0)}${select('shared-path','Prozářená tloušťka w',[['auto','Odvodit t / 2t'],['manual','Zadat skutečnou dráhu']])}${field('shared-penetrated','Skutečné w (mm)',20,'Bez vzduchu; včetně převýšení a šikmé dráhy.')}</div><p id="geometry-summary" role="status"></p><p id="geometry-skipped"></p><div class="work-panel-actions">${[['n','Počet expozic'],['ug','Neostrost'],['film','Čas filmu'],['cr','CR']].map(([id,l])=>`<label class="work-check"><input type="checkbox" id="shared-target-${id}" checked>${l}</label>`).join('')}</div><div class="work-panel-actions"><button id="geometry-apply" type="button" class="primary-button">Přenést vybrané údaje</button></div>`)+
 panel('compare-panel','Porovnání variant','<p id="compare-description"></p><button id="compare-refresh" class="secondary-button" type="button">Načíst aktuální zadání</button><div id="comparison-grid" class="comparison-grid"></div>');
 let pref={};try{pref=JSON.parse(w.localStorage.getItem('rt_job_context_v1'))||{};}catch{}
 by('job-part').value=typeof pref.part==='string'?pref.part:'';by('job-weld').value=typeof pref.weld==='string'?pref.weld:'';
 for(const [key,id]of Object.entries(geometryIds))if(typeof pref.geometry?.[key]==='string')by(id).value=pref.geometry[key];
 const geometryValues=()=>Object.fromEntries(Object.entries(geometryIds).map(([key,id])=>[key,by(id).value]));
 const preference=()=>{try{w.localStorage.setItem('rt_job_context_v1',JSON.stringify({job:by('job-select').value,part:by('job-part').value,weld:by('job-weld').value,geometry:geometryValues()}));}catch{}};
 function jobContext(){const job=by('job-select').selectedOptions[0];by('result-job-context').textContent=by('job-select').value?[job?.textContent,by('job-part').value.trim()||'Doplňte díl',by('job-weld').value.trim()||'Doplňte svar'].join(' · '):'Vyberte zakázku, díl a svar.';}
 function open(id,button){returnFocus=button||d.activeElement;for(const p of d.querySelectorAll('.work-panel')){p.hidden=p.id!==id;p.querySelector('.panel-message').textContent='';}activePanel=id;by('workflow-panels').hidden=false;by('app-surface').inert=true;d.body.classList.add('panel-open');by('connection-popover').open=false;returnFocus?.setAttribute?.('aria-expanded','true');by(id+'-title').focus();}
 function close(){if(activePanel)by(activePanel).hidden=true;by('workflow-panels').hidden=true;by('app-surface').inert=false;d.body.classList.remove('panel-open');activePanel=null;returnFocus?.setAttribute?.('aria-expanded','false');returnFocus?.focus();}
 on(by('workflow-panels'),'click',e=>{if(e.target===by('workflow-panels')||e.target.closest('[data-close-panel]'))close();});on(d,'keydown',e=>{if(!activePanel)return;if(e.key==='Escape'){e.preventDefault();close();}else if(activePanel)trapFocus(e,by(activePanel));});
 function refresh(){if(stopped)return;entries=store.entries();const selected=by('job-select').value||pref.job||'';const jobs=entries.filter(e=>e.kind==='job').sort((a,b)=>b.createdAt.localeCompare(a.createdAt));by('job-select').innerHTML='<option value="">Bez zakázky</option>'+jobs.map(j=>`<option value="${esc(j.id)}">${esc(j.name)}</option>`).join('');if(jobs.some(j=>j.id===selected))by('job-select').value=selected;jobNames=new Map(jobs.map(j=>[j.id,j.name]));historyIndex=entries.filter(e=>e.kind==='calculation').map(e=>({entry:e,search:[jobNames.get(e.jobId),e.part,e.weld,KINDS[e.context?.kind]].join(' ').toLocaleLowerCase('cs-CZ')})).sort((a,b)=>b.entry.createdAt.localeCompare(a.entry.createdAt));jobContext();if(activePanel==='history-panel')renderHistory();}
 function localStatus(error){by('storage-status').dataset.state=error?'error':'local';by('storage-status').textContent=error||'Zakázky a historie se ukládají pouze v tomto zařízení';}
 async function persist(entry){if(!readyForStorage)throw new Error('Úložiště není připravené. Povolte data webu a otevřete aplikaci znovu.');try{await store.add(entry);refresh();localStatus();}catch(error){localStatus(error.message);throw error;}}
 on(w,'focus',()=>{if(readyForStorage)store.reload().then(refresh).catch(error=>localStatus(error.message));});
 on(by('job-new'),'click',()=>{open('job-panel',by('job-new'));by('job-name').focus();});
 async function createJob(){const button=by('job-create');if(button.disabled)return;const hadFocus=d.activeElement===button;if(hadFocus)by('job-panel-title').focus();button.disabled=true;try{const name=by('job-name').value.trim();if(!name||name.length>120){by('job-name').focus();throw new Error('Zadejte název zakázky do 120 znaků.');}const job={id:w.crypto.randomUUID(),kind:'job',name,createdAt:new Date().toISOString()};await persist(job);by('job-select').value=job.id;pref.job=job.id;preference();jobContext();by('job-name').value='';close();message('Zakázka vytvořena. Doplňte díl a číslo svaru.');}catch(error){message(error.message,true);}finally{button.disabled=false;if(hadFocus&&activePanel==='job-panel'&&d.activeElement===by('job-panel-title'))button.focus();}}
 on(by('job-create'),'click',createJob);on(by('job-name'),'keydown',e=>{if(e.key==='Enter'&&!by('job-create').disabled){e.preventDefault();createJob();}});
 for(const id of ['job-select','job-part','job-weld'])on(by(id),'input',()=>{pref.job=by('job-select').value;preference();jobContext();renderHistory();});
 async function saveContext(context){const entry=historyEntry({id:w.crypto.randomUUID(),jobId:by('job-select').value,part:by('job-part').value,weld:by('job-weld').value,context});await persist(entry);message('Výpočet uložen do místní historie.');}
 on(by('history-save'),'click',async()=>{by('history-save').disabled=true;try{await saveContext(app.captureCalculation());}catch(error){message(error.message,true);if(!by('job-select').value)by('job-select').focus();else if(!by('job-part').value.trim())by('job-part').focus();else if(!by('job-weld').value.trim())by('job-weld').focus();}finally{by('history-save').disabled=false;}});
 function renderHistory(){if(activePanel!=='history-panel')return;const query=by('history-search').value.trim().toLocaleLowerCase('cs-CZ');const rows=historyIndex.filter(({entry:e,search})=>(by('history-scope').value==='all'||e.jobId===by('job-select').value)&&search.includes(query)).map(r=>r.entry);
  const pages=Math.max(1,Math.ceil(rows.length/PAGE_SIZE));historyPage=Math.min(historyPage,pages-1);const visible=rows.slice(historyPage*PAGE_SIZE,(historyPage+1)*PAGE_SIZE);
  by('history-page-status').textContent=rows.length?`${historyPage*PAGE_SIZE+1}–${Math.min((historyPage+1)*PAGE_SIZE,rows.length)} z ${rows.length}`:'Žádné záznamy';by('history-prev').disabled=historyPage===0;by('history-next').disabled=historyPage===pages-1;
  by('history-list').innerHTML=visible.length?visible.map(e=>`<article class="history-card"><h4>${esc(KINDS[e.context.kind])} · ${esc(e.weld)}</h4><div>${esc(jobNames.get(e.jobId)||'Zakázka')} / ${esc(e.part)}</div><strong class="history-result">${esc(e.result.summary)}</strong><p>${esc(e.result.status==='pass'?'Posuzované kritérium splněno':e.result.status==='fail'?'Posuzované kritérium nesplněno':e.result.status==='limit'?'Mimo rozsah odečtu':'Výpočet / odhad v rozsahu daného modelu')}</p><div class="history-meta">${esc(new Date(e.createdAt).toLocaleString('cs-CZ'))} · model ${esc(e.modelVersion)} · uloženo v zařízení</div><details><summary>Původní vstupy a reference</summary><dl>${Object.entries(e.context.inputs).filter(([,v])=>v!==null&&v!=='').map(([key,value])=>`<dt>${esc(labels[key]||key)}</dt><dd>${esc(typeof value==='boolean'?value?'Ano':'Ne':typeof value==='number'?fmt(value):values[value]||value)}</dd>`).join('')}</dl>${e.context.reference?`<p>Reference: ${esc(e.context.reference.name)} · ${esc(e.context.reference.measuredAt)} · ${fmt(e.context.reference.exposure)} mA·min · SNR_N ${fmt(e.context.reference.achievedSnr)}</p>`:''}</details><button type="button" class="secondary-button" data-restore="${esc(e.id)}" ${validEntry(e)?'':'disabled'}>Otevřít vstupy v kalkulátoru</button>${validEntry(e)?'':'<p>Tento historický záznam nelze ověřit v podporované verzi. Původní údaje lze číst a exportovat.</p>'}</article>`).join(''):'<p>V tomto výběru zatím nejsou uložené výpočty. Vyberte zakázku, doplňte díl a svar a použijte „Uložit k tomuto svaru“.</p>';
 }
 on(by('history-open'),'click',()=>{historyPage=0;open('history-panel',by('history-open'));renderHistory();});for(const id of ['history-search','history-scope'])on(by(id),'input',()=>{historyPage=0;renderHistory();});
 for(const [id,delta]of [['history-prev',-1],['history-next',1]])on(by(id),'click',()=>{historyPage+=delta;renderHistory();by('history-panel-title').focus();by('history-panel').scrollTop=0;});
 on(by('history-list'),'click',e=>{const button=e.target.closest('[data-restore]');if(!button)return;const record=entries.find(r=>r.id===button.dataset.restore);if(!record)return;try{if(!validEntry(record))throw new Error('Historický záznam je rozporný nebo používá nepodporovaný model. Původní údaje zůstávají dostupné pro export.');app.restoreCalculation(clone(record.context));by('job-select').value=record.jobId;by('job-part').value=record.part;by('job-weld').value=record.weld;pref.job=record.jobId;preference();jobContext();close();message(`Vstupy otevřeny v aktuálním kalkulátoru. Původní výsledek „${record.result.summary}“ zůstává v historii.${record.context.kind==='xray'&&record.context.inputs.mode==='manual'?' Platnost vlastní reference před novým použitím znovu potvrďte.':''}`);}catch(error){message(error.message,true);}});

 function renderGeometry(){const g=geometryValues();by('shared-penetrated').disabled=g.pathMode!=='manual';by('shared-diameter').disabled=g.technique==='flat';try{const r=sharedGeometry(g);by('geometry-summary').textContent=`t = ${fmt(r.t)} mm · w = ${fmt(r.w)} mm · SFD = ${fmt(r.sfd)} mm · zdroj–první povrch = ${fmt(r.f)} mm. ${r.assumption}`;by('geometry-summary').dataset.error='false';by('geometry-skipped').textContent=r.skipped.join(' ');by('geometry-apply').disabled=false;by('shared-target-n').disabled=!r.maps.n;}catch(error){by('geometry-summary').textContent=error.message;by('geometry-summary').dataset.error='true';by('geometry-skipped').textContent='';by('geometry-apply').disabled=true;}}
 on(by('geometry-open'),'click',()=>{renderGeometry();open('geometry-panel',by('geometry-open'));});for(const id of Object.values(geometryIds))on(by(id),'input',()=>{renderGeometry();preference();});
 on(by('geometry-apply'),'click',()=>{try{const r=sharedGeometry(geometryValues()),selected=Object.entries(r.maps).filter(([key])=>by('shared-target-'+key).checked);if(!selected.length)throw new Error('Vyberte alespoň jeden kalkulátor.');app.applyForm(Object.assign({},...selected.map(([,map])=>map)));close();message(`Geometrie přenesena: ${selected.map(([key])=>({n:'počet expozic',ug:'neostrost',film:'čas filmu',cr:'CR'}[key])).join(', ')}. t = ${fmt(r.t)} mm, w = ${fmt(r.w)} mm. Zkontrolujte rozsah každého kalkulátoru.`);preference();}catch(error){message(error.message,true);}});
 function loadComparison(){try{base=app.captureCalculation();const fields=variantFields(base);if(!fields.length)throw new Error('Pro porovnání časů CR přepněte na odhad z referenčního měření.');const distance=fields[0].key;variants=[{}, {[distance]:base.inputs[distance]*1.2},{[distance]:base.inputs[distance]*.8}];by('compare-description').textContent=`${KINDS[base.kind]} · zadání převzaté při otevření porovnání. Ostatní podmínky zůstávají stejné.${base.kind==='xray'&&base.inputs.mode==='manual'?' Film nelze měnit bez nové reference.':''} ${base.kind==='ug'?'Hodnotí se geometrická neostrost a minimální vzdálenost.':base.kind==='n'?'Porovnává se počet expozic podle stejného nomogramu.':'Porovnává se expoziční čas; kvalitu nového snímku ověřte měřením.'}`;
  by('comparison-grid').innerHTML=variants.map((changes,i)=>`<article class="comparison-card" id="variant-${i}"><h4>${i===0?'Výchozí zadání':'Varianta '+String.fromCharCode(65+i)}</h4>${fields.map(f=>`<div class="compare-field"><label for="variant-${i}-${f.key}">${f.label}</label>${f.options?`<select id="variant-${i}-${f.key}" data-variant="${i}" data-key="${f.key}" ${i===0?'disabled':''}>${f.options.map(v=>`<option ${v===(changes[f.key]??base.inputs[f.key])?'selected':''}>${v}</option>`).join('')}</select>`:`<input id="variant-${i}-${f.key}" data-variant="${i}" data-key="${f.key}" inputmode="decimal" value="${esc(changes[f.key]??base.inputs[f.key])}" ${i===0?'readonly':''}>`}</div>`).join('')}<div class="comparison-result" id="variant-result-${i}" aria-live="polite"></div><p id="variant-detail-${i}"></p><button type="button" class="secondary-button" data-use-variant="${i}" ${i===0?'hidden':''}>Použít variantu</button></article>`).join('');variants.forEach((_,i)=>renderVariant(i));
 }catch(error){base=null;by('comparison-grid').innerHTML='';by('compare-description').textContent=error.message;message(error.message,true);}}
 function renderVariant(i){const card=by('variant-'+i),use=card.querySelector('[data-use-variant]');try{const r=compareVariant(base,variants[i]);card.dataset.valid='true';card.dataset.state=r.result.status;by('variant-result-'+i).textContent=r.result.summary;const v=r.result.values;by('variant-detail-'+i).textContent=(i===0?'Výchozí hodnota.':r.percent===null?'Rozdíl nelze určit.':`Rozdíl ${r.percent>=0?'+':''}${fmt(r.percent)} % vůči výchozímu zadání.`)+(base.kind==='ug'?` ${v.passes?'Minimální vzdálenost splněna.':'Minimální vzdálenost NESPLNĚNA.'}`:r.result.status==='limit'?' Mimo rozsah počtu v nomogramu.':'');use.disabled=false;}catch(error){card.dataset.valid='false';card.dataset.state='error';by('variant-result-'+i).textContent='Nelze vypočítat';by('variant-detail-'+i).textContent=error.message;use.disabled=true;}}
 on(by('compare-open'),'click',()=>{loadComparison();open('compare-panel',by('compare-open'));});on(by('compare-refresh'),'click',loadComparison);
 on(by('comparison-grid'),'input',e=>{const el=e.target;if(!el.hasAttribute('data-variant')||Number(el.dataset.variant)===0)return;variants[Number(el.dataset.variant)][el.dataset.key]=el.value;renderVariant(Number(el.dataset.variant));});
 on(by('comparison-grid'),'click',e=>{const button=e.target.closest('[data-use-variant]');if(!button)return;try{const r=compareVariant(base,variants[Number(button.dataset.useVariant)]);app.restoreCalculation(r.context,{preserveCalibration:true});close();message('Varianta přenesena do kalkulátoru. Výsledek lze nyní uložit do zakázky.');}catch(error){message(error.message,true);}});
 const dataTools=initDataTools({document:d,app,store,open:()=>open('data-panel',by('data-open')),onArchiveChanged:async()=>{pref.job='';by('job-select').value='';refresh();preference();localStatus();},onRestored:async()=>{refresh();localStatus();}});
 jobContext();renderGeometry();
 const ready=store.init().then(async()=>{if(stopped)return;readyForStorage=true;refresh();await dataTools.ready();if(!stopped)return localStatus();}).catch(error=>{if(stopped)return;by('storage-status').dataset.state='error';by('storage-status').textContent=error.message;message('Zakázky nyní nelze bezpečně uložit. Výpočty můžete dál používat.',true);});
 return {ready,store,destroy(){stopped=true;abort.abort();dataTools.destroy();store.close();}};
}
